format = """
$directory\
[](fg:#DA627D bg:#2DD881)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#2DD881 bg:#06969A)\
$git_branch\
$git_status\
[](fg:#06969A bg:#33658A)\
$docker_context\
$time\
[ ](fg:#33658A)
"""
right_format = """$cmd_duration"""

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"codes" = "📁"

[c]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#06969A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#2DD881"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ✦ $time ]($style)'

[cmd_duration]
min_time = 500
format = '[🚀 $duration◀](green)'
